file_58 = read.csv('percents_58.csv')
file_59 = read.csv('percents_59.csv')
file_60 = read.csv('percents_60.csv')
mean(as.numeric(as.vector(unlist(file_58))))
mean(as.numeric(as.vector(unlist(file_59))))
mean(as.numeric(as.vector(unlist(file_60))))
sd(as.numeric(as.vector(unlist(file_58))))
sd(as.numeric(as.vector(unlist(file_59))))
sd(as.numeric(as.vector(unlist(file_60))))